In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a


array([1, 2, 3])

In [4]:
a.tolist()#change numpy array to list

[1, 2, 3]

In [5]:
a.shape#get shape o the arrray 

(3,)

In [6]:
a.ndim
#get number of dimension of array

1

In [7]:
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [8]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
b.shape

(2, 3)

In [10]:
b.ndim

2

In [11]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [12]:
print(a)

[1 2 3]


In [13]:
#get type  of numpy array
a.dtype

dtype('int32')

In [14]:
a=np.array([1,2,3],dtype='int16')

In [15]:
a.dtype#now it takes lesser valuues

dtype('int16')

In [16]:
a.itemsize #get the size of item stored in the array

2

In [17]:
#get the number of elements in the array
a.size

3

In [18]:
#get the size of element in the array
a.size*a.itemsize

6

In [19]:
#or you van directly use
a.nbytes

6

# ACCESSING AND CAHNGING ELEMENTS,ROWS,COLUMNS ETC.

In [20]:
c=np.array([[1,2,3,4,5,6,7],[45,21,35,6,4,8,56]])

In [21]:
print(c)

[[ 1  2  3  4  5  6  7]
 [45 21 35  6  4  8 56]]


In [22]:
#get specific element by[r,c]
c[1,5]

8

In [23]:
#or 
c[1,-2]

8

In [24]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [45, 21, 35,  6,  4,  8, 56]])

In [25]:
#get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
#get a specific column
c[:,2]

array([ 3, 35])

In [27]:
#gettting liittle more extra  [startindex:finalindex:steps size]
c[0,0:7:2]

array([1, 3, 5, 7])

*3d example

In [28]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [29]:
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
#now i want acces 4
a[0,1,1]

4

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.ones((4,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [35]:
np.full((3,3),56)#desired value matrix

array([[56, 56, 56],
       [56, 56, 56],
       [56, 56, 56]])

In [36]:
#we can generate any array of type of different values with some constant set of values
a=np.array([[1,2,3,4],[5,6,7,8]])

In [37]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
np.full_like(a,27)#like thhiss

array([[27, 27, 27, 27],
       [27, 27, 27, 27]])

In [39]:
np.full(a.shape,27)#2nd way

array([[27, 27, 27, 27],
       [27, 27, 27, 27]])

In [40]:
#array of random decimal numbers
np.random.rand(4,4)

array([[0.86016694, 0.30009945, 0.87538812, 0.6635487 ],
       [0.34633388, 0.97106213, 0.91555891, 0.30341306],
       [0.54400431, 0.76913518, 0.17468965, 0.48373122],
       [0.67778343, 0.26853801, 0.795498  , 0.42832274]])

In [41]:
a.shape

(2, 4)

In [42]:
#if we want to generate array of like different array
np.random.random_sample(a.shape)

array([[0.91871189, 0.83693226, 0.35300278, 0.64355939],
       [0.46445553, 0.36562645, 0.48097109, 0.49479296]])

In [43]:
#if we want to generate array of some random integer values
np.random.randint(3,size=(3,3))#first one attribute is for values under which randomm generates values basicallly 0 to 3-1

array([[0, 2, 2],
       [1, 0, 2],
       [1, 0, 0]])

In [44]:
np.random.randint(-5,5,size=(3,3))#now we give the range of values between which it generates random values 
#initial one is exclusive

array([[-1,  0, -3],
       [ 1,  4,  1],
       [ 2, -1, -2]])

In [45]:
# we can repeate a single dimensional to build another dimensional array
a=np.array([[1,2,3]])
print(np.repeat(a,3,axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
np.repeat(a,6,axis=1)

array([[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3]])

In [47]:
np.repeat(a,6,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [48]:
ar=np.zeros((5,5))

In [49]:
print(ar)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [50]:
ar[0]=1

In [51]:
ar

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
ar[-1]=1

In [53]:
ar

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [54]:
ar[:,0]=1

In [55]:
ar[:,-1]=1

In [56]:
ar

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
ar[2,2]=9.0


In [58]:
ar

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
#2nd method of making the above array
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### BE CAREFUL WHILE COPYING ARRAYS

In [60]:
a=np.array([1,2,3])
b=a
print(b)

[1 2 3]


In [61]:
b[0]=100

In [62]:
print(b)

[100   2   3]


In [63]:
print(a)#here we came into problem as u can see while changing value to b value of a also changes

[100   2   3]


### in the above as a and b pointing to same object any variation happens at object thats why it chnages the both values


In [64]:
a=np.array([1,2,3])

In [65]:
a

array([1, 2, 3])

In [66]:
b=a.copy()#if we use the copy it helps us from above distruction

In [67]:
b

array([1, 2, 3])

In [68]:
b[0]=100

In [69]:
b

array([100,   2,   3])

In [70]:
a

array([1, 2, 3])

# mathematics

In [71]:
a=np.array([1,2,3,4])

In [72]:
a

array([1, 2, 3, 4])

In [73]:
a+2

array([3, 4, 5, 6])

In [74]:
a-2

array([-1,  0,  1,  2])

In [75]:
a*2

array([2, 4, 6, 8])

In [76]:
a/2


array([0.5, 1. , 1.5, 2. ])

In [77]:
b=np.array([1,2,0,1])

In [78]:
a+b

array([2, 4, 3, 5])

In [79]:
a **2

array([ 1,  4,  9, 16], dtype=int32)

In [80]:
#take the sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [81]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### LINEAR ALGEBRA


In [82]:
a=np.ones((3,3))
b=np.full((3,2),5)
a.dot(b)

array([[15., 15.],
       [15., 15.],
       [15., 15.]])

In [83]:
np.matmul(a,b) #another way

array([[15., 15.],
       [15., 15.],
       [15., 15.]])

In [84]:
#find the determinante of matrix
c=np.identity(3)
np.linalg.det(c)

1.0

### STATISTICS LIKE MEAN,MAX.ETC

In [85]:
stats=np.array([[1,2,3],[4,5,6]])

In [86]:
np.min(stats)

1

In [87]:
np.max(stats)

6

In [88]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.min(stats ,axis=0)

array([1, 2, 3])

In [90]:
np.min(stats,axis=1)

array([1, 4])

In [91]:
np.sum(stats)

21

In [92]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [93]:
np.sum(stats,axis=1)

array([ 6, 15])

### reorganizing arrays

In [94]:
before=np.array([[1,2,3,4],[5,6,7,8]])

In [95]:
before.shape

(2, 4)

In [96]:
after=before.reshape((4,2))

In [97]:
after.shape

(4, 2)

In [98]:
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [99]:
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [100]:
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [101]:
#vertically stacking arrays and matrices or vectors

In [102]:
v1=np.array([1,2,3,4])

In [103]:
v2=np.array([5,6,7,8])

In [104]:
np.vstack([v1,v2,v2,v2,v1])#we can stack as many times as we want

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [105]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack([h1,h2])#we can stack as many time as we want

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## MISCELLANEOUS
##### Load data from file

In [107]:
arr=np.genfromtxt('data/data.txt',delimiter=',',dtype='int')

In [108]:
arr


array([[1, 2, 3, 4, 5, 6, 7, 8],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2]])

### Boolean masking and advance indexing

In [109]:
arr[arr>1]

array([2, 3, 4, 5, 6, 7, 8, 2, 2, 2, 2, 2, 2, 2, 2])

In [110]:
#we can index as a list in numpy

In [111]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[[1,5,8]]

array([2, 6, 9])

In [112]:
np.any(arr>2,axis=0)

array([False, False,  True,  True,  True,  True,  True,  True])

In [113]:
np.all(arr>2,axis=1)

array([False, False, False, False])

In [114]:
np.all(arr>2,axis=0)

array([False, False, False, False, False, False, False, False])

In [115]:
d=np.zeros((5,5))

In [116]:
count=1
for i in range(5):
    for j in range(5):
        d[i,j]=count
        count+=1

In [117]:
d

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])