In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a


array([1, 2, 3])

In [4]:
a.tolist()#change numpy array to list

[1, 2, 3]

In [5]:
a.shape#get shape o the arrray 

(3,)

In [6]:
a.ndim
#get number of dimension of array

1

In [7]:
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [8]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
b.shape

(2, 3)

In [10]:
b.ndim

2

In [11]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [12]:
print(a)

[1 2 3]


In [13]:
#get type  of numpy array
a.dtype

dtype('int32')

In [14]:
a=np.array([1,2,3],dtype='int16')

In [15]:
a.dtype#now it takes lesser valuues

dtype('int16')

In [16]:
a.itemsize #get the size of item stored in the array

2

In [17]:
#get the number of elements in the array
a.size

3

In [18]:
#get the size of element in the array
a.size*a.itemsize

6

In [19]:
#or you van directly use
a.nbytes

6

# ACCESSING AND CHANGING ELEMENTS,ROWS,COLUMNS ETC.

In [20]:
c=np.array([[1,2,3,4,5,6,7],[45,21,35,6,4,8,56]])

In [21]:
print(c)

[[ 1  2  3  4  5  6  7]
 [45 21 35  6  4  8 56]]


In [22]:
#get specific element by[r,c]
c[1,5]

8

In [23]:
#or 
c[1,-2]

8

In [24]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [45, 21, 35,  6,  4,  8, 56]])

In [25]:
#get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
#get a specific column
c[:,2]

array([ 3, 35])

In [27]:
#gettting liittle more extra  [startindex:finalindex:steps size]
c[0,0:7:2]

array([1, 3, 5, 7])

*3d example

In [28]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [29]:
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
#now i want acces 4
a[0,1,1]

4

In [31]:
np.zeros((3,3)) #all values of (n,n) matrix are 0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.identity(3)  #(n) means n*n identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.ones((4,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [37]:
np.full((3,3),45) #desired value matrix

array([[45, 45, 45],
       [45, 45, 45],
       [45, 45, 45]])

In [38]:
#we can generate any array of type of different values with some constant set of values
a=np.array([[1,2,3,4],[5,6,7,8]])

In [39]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [40]:
np.full_like(a,27)#like thhiss

array([[27, 27, 27, 27],
       [27, 27, 27, 27]])

In [41]:
np.full(a.shape,27)#2nd way

array([[27, 27, 27, 27],
       [27, 27, 27, 27]])

In [51]:
#array of random decimal numbers
np.random.rand(2,2) #n*n matrix will be created with some random decimal values

array([[0.99999537, 0.79159813],
       [0.04608962, 0.54486672]])

In [52]:
a.shape

(2, 4)

In [53]:
#if we want to generate array of like different array
np.random.random_sample(a.shape)

array([[0.08684659, 0.68640246, 0.71552614, 0.05219838],
       [0.8015525 , 0.04185676, 0.82024022, 0.88362   ]])

In [71]:
#if we want to generate array of some random integer values
np.random.randint(10,size=(3,3))#first one attribute is for values under which randomm generates values basicallly 0 to 10-1

array([[8, 9, 5],
       [6, 4, 8],
       [8, 5, 0]])

In [97]:
np.random.randint(-5,5,size=(3,3))#now we give the range of values between which it generates random values 
#initial value of range is exclusive

array([[-3, -4, -4],
       [-5, -5,  0],
       [ 0, -1, -3]])

In [100]:
# we can repeate a single dimensional to build another dimensional array
a=np.array([[1,2,3]])
print(np.repeat(a,3,axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [101]:
np.repeat(a,6,axis=1)

array([[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3]])

In [102]:
np.repeat(a,6,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [103]:
ar=np.zeros((5,5))

In [104]:
print(ar)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [105]:
ar[0]=1

In [106]:
ar

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [107]:
ar[-1]=1

In [53]:
ar

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [108]:
ar[:,0]=1

In [109]:
ar[:,-1]=1

In [110]:
ar

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [111]:
ar[2,2]=9.0


In [112]:
ar

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [113]:
#2nd method of making the above array
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### BE CAREFUL WHILE COPYING ARRAYS.

Since if we make any changes in duplicate array it will effect the primary array as well

In [129]:
a=np.array([1,2,3])
b=a
print(b)

[1 2 3]


In [130]:
b[0]=100

In [131]:
print(b)

[100   2   3]


In [132]:
print(a)#here we came into problem as u can see while changing value to b value of a also changes

[100   2   3]


In [133]:
a is b

True

### in the above as a and b pointing to same object any variation happens at object thats why it chnages the both values


In [134]:
a=np.array([1,2,3])

In [135]:
a

array([1, 2, 3])

In [136]:
b=a.copy() #if we use the copy it helps us from above distruction.
#and also copy makes a new object or instance with the same value

In [137]:
b

array([1, 2, 3])

In [138]:
a is b

False

In [139]:
a == b

array([ True,  True,  True])

In [140]:
b[0]=100

In [141]:
b

array([100,   2,   3])

In [142]:
a

array([1, 2, 3])

# mathematics

In [143]:
a=np.array([1,2,3,4])

In [144]:
a

array([1, 2, 3, 4])

In [145]:
a+2

array([3, 4, 5, 6])

In [146]:
a-2

array([-1,  0,  1,  2])

In [147]:
a*2

array([2, 4, 6, 8])

In [149]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [150]:
#all the above operations doesn't change the original value of a

In [151]:
b=np.array([1,2,0,1])

In [152]:
a+b

array([2, 4, 3, 5])

In [153]:
a **2

array([ 1,  4,  9, 16], dtype=int32)

In [154]:
#take the sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [155]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### LINEAR ALGEBRA


In [157]:
a=np.ones((3,3))
b=np.full((3,2),5)

In [158]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [159]:
b

array([[5, 5],
       [5, 5],
       [5, 5]])

In [160]:
a.dot(b)

array([[15., 15.],
       [15., 15.],
       [15., 15.]])

In [162]:
b.dot(a) #as column number of first matrix should be equal to row number of second matrix

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [163]:
np.matmul(a,b) #another way of finding the dot product

array([[15., 15.],
       [15., 15.],
       [15., 15.]])

In [164]:
#find the determinante of matrix
c=np.identity(3)
np.linalg.det(c)

1.0

### STATISTICS LIKE MEAN,MAX.ETC

In [184]:
stats=np.array([[1,2,3],[4,5,6]])

In [185]:
np.min(stats)

1

In [186]:
np.max(stats)

6

In [187]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [188]:
np.min(stats ,axis=0) #axis = 0 means minimum values column wise 

array([1, 2, 3])

In [189]:
np.min(stats,axis=1)

array([1, 4])

In [190]:
np.sum(stats)

21

In [191]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [192]:
np.sum(stats,axis=1)

array([ 6, 15])

### reorganizing arrays

In [193]:
before=np.array([[1,2,3,4],[5,6,7,8]])

In [194]:
before.shape

(2, 4)

In [195]:
after=before.reshape((4,2))

In [196]:
after.shape

(4, 2)

In [197]:
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [198]:
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [201]:
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [202]:
#vertically stacking arrays and matrices or vectors

In [203]:
v1=np.array([1,2,3,4])

In [224]:
v2=np.array([5,6,7,8])

In [225]:
np.vstack([v1,v2,v2,v2,v1])#we can stack as many times as we want vstack->vertical stack
#note-> column number should be same to perform vstack

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [218]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))


In [219]:
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [220]:
h2

array([[0., 0.],
       [0., 0.]])

In [221]:
np.hstack([h1,h2])#we can stack as many time as we want
#note -> row number should be same of both matrices which is conacatenated

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## MISCELLANEOUS
##### Load data from file

In [226]:
arr=np.genfromtxt('data/data.txt',delimiter=',',dtype='int')

In [227]:
arr


array([[1, 2, 3, 4, 5, 6, 7, 8],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2]])

### Boolean masking and advance indexing

In [229]:
arr[arr>1]

array([2, 3, 4, 5, 6, 7, 8, 2, 2, 2, 2, 2, 2, 2, 2])

In [230]:
#we can index as a list in numpy

In [231]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[[1,5,8]]

array([2, 6, 9])

In [112]:
np.any(arr>2,axis=0)

array([False, False,  True,  True,  True,  True,  True,  True])

In [232]:
np.any(arr>2,axis=1)

array([ True, False, False, False])

In [233]:
np.all(arr>2,axis=1)

array([False, False, False, False])

In [234]:
np.all(arr>2,axis=0)

array([False, False, False, False, False, False, False, False])

In [235]:
d=np.zeros((5,5))

In [237]:
count=1
for i in range(5):
    for j in range(5):
        d[i,j]=count
        count+=1

In [238]:
d

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [239]:
d.mean()

13.0

In [240]:
d.sum()

325.0