In [22]:
import numpy as np

In [23]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [24]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
a.shape

(2, 4)

In [26]:
a.sum()

36

In [27]:
a[0].sum()

10

In [28]:
a[1].sum()

26

In [29]:
a[0,:2].sum()

3

In [30]:
a+10


array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [31]:
a+=100


In [32]:
a

array([[101, 102, 103, 104],
       [105, 106, 107, 108]])

In [33]:
a+10

array([[111, 112, 113, 114],
       [115, 116, 117, 118]])

In [34]:
a

array([[101, 102, 103, 104],
       [105, 106, 107, 108]])

In [35]:
a.sum(axis=0)

array([206, 208, 210, 212])

In [36]:
a.sum(axis=1)

array([410, 426])

In [37]:
a=np.arange(5)

In [39]:
a

array([0, 1, 2, 3, 4])

In [40]:
a+20

array([20, 21, 22, 23, 24])

In [42]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
l=[1,2,3,4,5,6,7,8,9]
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
f=np.array(l).reshape(3,3)

In [46]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
ab=list()

In [49]:
cd=f.mean(axis=0)

In [50]:
cd

array([4., 5., 6.])

In [51]:
ab.append(cd)

In [52]:
ab

[array([4., 5., 6.])]

In [53]:
cd=f.mean(axis=1)

In [55]:
cd

array([2., 5., 8.])

In [54]:
ab.append(cd)

In [56]:
ab

[array([4., 5., 6.]), array([2., 5., 8.])]

In [57]:
ab[0]

array([4., 5., 6.])

In [58]:
ab[1]

array([2., 5., 8.])

In [59]:
f.mean()

5.0

In [60]:
dicti=dict()

In [61]:
dicti={'mean':[list(ab[0]),list(ab[1]),a.mean()]}

In [62]:
dicti

{'mean': [[4.0, 5.0, 6.0], [2.0, 5.0, 8.0], 2.0]}

In [63]:
print(dicti)

{'mean': [[4.0, 5.0, 6.0], [2.0, 5.0, 8.0], 2.0]}


In [64]:
type(dicti)

dict

In [65]:
type(dicti['mean'])

list

In [68]:
a.var(axis=0)

2.0