In [160]:
import numpy as np

In [161]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [162]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [163]:
np.arange(0,1,.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [164]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [165]:
#linspace will make an array in between the given range with equal difference 

In [166]:
np.linspace(0,1,5,False) #false means last limit is not in the range

array([0. , 0.2, 0.4, 0.6, 0.8])

In [167]:
np.linspace(0,1,5,True) #true means last limit is in the range

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [168]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [169]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [170]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [171]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [172]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [173]:
a=np.empty((5,5))

In [174]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### empty, unlike zeros does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [175]:
np.identity(3,dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [176]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [177]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [178]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### numpy.eye(R, C = None, k = 0, dtype = type <‘float’>) : –The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k. A positive k is for the upper diagonal, a negative k is for the lower, and a  0 k (default) is for the main diagonal.

In [179]:
np.eye(8,4,k=-2) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [180]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [181]:
"hello world"[6]

'w'

In [182]:
print(np.__version__)

1.21.2


In [183]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [184]:
0*np.arange(10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [185]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [186]:
np.ones((2,2),dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

In [187]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [188]:
a=np.ones_like(a)

In [189]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [190]:
5*np.ones((4,4),dtype=np.int8)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

In [191]:
np.random.randint(10,size=(3,3)) #random generate number inbetween 0 to n-1 and make matrix of given size k*k
#np.random.randint(n,size=(k,k))

array([[3, 6, 1],
       [0, 9, 4],
       [6, 8, 5]])

In [192]:
np.random.randint(2,size=3)

array([0, 1, 0])

In [193]:
np.random.random(10)

array([0.7230088 , 0.55615546, 0.33147206, 0.81214611, 0.83141222,
       0.48789345, 0.28829426, 0.49977632, 0.96237924, 0.13610182])

In [194]:
np.arange(3,10,2)#numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
#Return evenly spaced values within a given interval.

array([3, 5, 7, 9])

In [195]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [196]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [197]:
a.itemsize

8

In [198]:
a=np.arange(10)

In [199]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [200]:
a[[0,2,-1]]

array([0, 2, 9])

In [202]:
a[::2]

array([0, 2, 4, 6, 8])

In [211]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [220]:
X[1:-1,1:-1]

array([[ 6,  7],
       [10, 11]])

In [221]:
X[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [222]:
X[2:,2:]

array([[11, 12],
       [15, 16]])

In [223]:
np.array(X,np.float16)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float16)

In [224]:
X.sort()

In [225]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [226]:
X[-1]=1

In [227]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [228]:
mask=X>5

In [229]:
mask

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [230]:
X[mask]

array([ 6,  7,  8,  9, 10, 11, 12])

In [231]:
X.all()

True

In [232]:
X[0]=0


In [233]:
X.all()

False

In [234]:
X.all(0)

array([False, False, False, False])